name: HTTP Header Checker

on:
  workflow_dispatch:
    inputs:
      url:
        description: "Website URL"
        required: true
        default: "https://jcevents.hotstar.com/"
        type: string

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Install requests
        run: pip install requests

      - name: Check Response Headers
        env:
          TARGET_URL: ${{ inputs.url }}
        run: python header_checker.py
